### ISSUE TITLE
Add ListGenericResources endpoint

### ISSUE THREAD

**Issue by alexashley** [rode/rode#45]
Name TBD. The `ListResources` RPC does a collapse on an occurrence's `resource.uri` field, returning unique `resource.uri`s. This isn't particularly helpful when trying to present a list of Docker images or NPM packages to a user in `rode-ui`, since they will see every single version of that image or package. 

This `ListGenericResources` endpoint would return only the unique set of names across all resources. We could do this by tracking those as a separate document type.

**Comment by pickjasmine** [comment]
Just thinking out loud about this endpoint... the UI currently shows some helper text that says you can search by either name or version. Do we want to still enable users to be able to search by version? Would that even be possible when using this new endpoint?

**Comment by alexashley** [comment]
Closed by #47, #48
