### ISSUE TITLE
Update policy validation to also check that violations.result includes 'message' and 'pass'

### ISSUE THREAD

**Issue by aalsabag** [rode/rode#57]
Currently the validation checks to see that a **pass** block and **violations** block returning a **result** object exists.
Confirm that the **result** block also contains a **pass** key and **message** key

**Comment by pickjasmine** [comment]
Could this also include an `id` key? I'm using it to ensure that each violation is unique.

**Comment by alexashley** [comment]
I think this was addressed in #59
