### ISSUE TITLE
Update fetch occurrences method

### ISSUE THREAD

**Issue by matt2m** [rode/rode#61]
Update fetch occurrences method in Rode to fetch build occurrences which reference the primary resource URI and compile a list of related resource URIs then fetch and return occurrences for all resource URIs

**Comment by ChrisSchreiber** [comment]
@alexashley brought up a good point that we should update the ListOccurrencesRequest to accept the resource URI instead of a filter since List Occurrences will need to make multiple calls to grafeas with different filters.
